import type { Metadata } from "next";
import "./globals.css";
import AppBar from "@/components/AppBar";
import ReduxProvider from "@/redux/ReduxProvider";
import { AppThemeContextProvider } from "@/context/AppThemeContext";

export const metadata: Metadata = {
  title: "Awesome App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {/* <Provider store={store}> */}
        <ReduxProvider>
          <AppThemeContextProvider>
            <div className="container">
              <AppBar />
              <main>{children}</main>
            </div>
          </AppThemeContextProvider>
        </ReduxProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
